site_name: Git Notes forBeginners
site_description: Git学習ノート
site_url: https://aigon3535.github.io/git-learning-notes/

theme:
  name: material
  language: ja


nav:
  - Home: index.md
  - 仕組み: 01_仕組み/index.md
  - コマンド:
      - 目次: 02_コマンド/index.md
      - 初級編: 02_コマンド/01_初級編.md
      - 中級編: 02_コマンド/02_中級編.md
      - stash: 02_コマンド/03_stash.md
  - 定着テスト: 03_定着テスト/index.md
  - トラブルQ&A: 09_トラブルQ&A/index.md

markdown_extensions:
  - admonition
